### PR TITLE
Include sets methods

### PR DESCRIPTION
**Pull request by troex**

### CODE REVIEW

**Comment by troex** [comment]
With this small change and little hack below I've been able to run Sidekiq client on top of `async-redis` in falcon

```ruby
module Sidekiq
  def self.redis=(hash)
    @redis = if hash.is_a?(ConnectionPool) || hash.is_a?(Async::Redis::Client)
      hash
    else
      Sidekiq::RedisConnection.create(hash)
    end
  end
end

Sidekiq.configure_client do |config|
  config.redis = Async::Redis::Client.new(...)
end
```

**Comment by troex** [comment]
oh there was actually another monkey patching, but it's more for async-redis actually:

```ruby
  # add ConnectionPool compatibility
  module Async
    module Redis
      class Client
        def with
          if Async::Task.current?
            yield(self)
          else
            Async { yield(self) }.wait
          end
        end
      end
    end
  end
```

**Comment by troex** [comment]
okay with sidekiq is wasn't that easy it works unless new queue is created or more events pushed at time because sidekiq uses "multi" to push data in buckets on higher load, but `multi` (transaction) implementation differs in `async-redis` and `redis-rb`.

Still enabling sets make sense.

**Comment by ioquatix** [comment]
Thanks for your effort, it looks like this PR was effectively already implemented. However, I appreciate your time and investigation regarding integration with Sidekiq. I think we should do more of that if possible and I'd welcome more PRs in that direction.

**Pull request closed without merging**
