### PR TITLE
Add missing hscan and add mapped_hmget & mapped_hmset

### PR DESCRIPTION
**Pull request by nburwell**
This adds `hscan` as a client method.

I'm proposing that these two methods that exist in the `redis-rb` gem also be added as convenience methods ([source](https://github.com/redis/redis-rb/blob/master/lib/redis/commands/hashes.rb#L65))
* `mapped_hmget`
* `mapped_hmset`

This allows developers to store and retrieve data using Ruby hashes, and would be consistent with how `hgetall` is currently implemented in the gem, where it converts the array of data to a hash.

By the way, following up on the comment discussion in my [previous PR](https://github.com/socketry/protocol-redis/pull/16#issuecomment-1574843908), regarding `eval` and `evalsha`: in thinking about this more, I am not convinced it will be an improvement to change those interfaces to match exactly the `redis-rb` gem. Since the default behavior in this protocol-redis gem is to pass through arguments to the socket, I think the logic that `redis-rb` [added here](https://github.com/redis/redis-rb/blob/master/lib/redis/commands/scripting.rb#L56-L71) to require arrays for the keys and values (and then [plumb](https://github.com/redis/redis-rb/blob/master/lib/redis/commands/scripting.rb#L110) the `numkeys` automatically based on the length of the keys array) is more confusing than helpful.

## Types of Changes

- New feature.

## Contribution

- [x] I added tests for my changes.
- [x] I tested my changes locally.
- [x] I agree to the [Developer's Certificate of Origin 1.1](https://developercertificate.org/).

### CODE REVIEW

**Comment by ioquatix** [comment]
I will merge this as I'm convinced by your position.

However, I slightly dislike the following:

1. The `mapped_` prefix doesn't immediately make me think of hash arguments/return values. However, for consistency's sake, we can add it, and if we want to add aliases later, that's also possible.
2. I'm also not super convinced we should be adding non-fundamental methods. My original goal with these methods was 1:1 with the Redis methods/commands. What we have here is an extension of those methods around type coercion. As you said with `eval` too... It's easier if we just expose the bare methods with the arguments, and provide other constructs that make it convenient for the user.

Because the cost of this PR is fairly low, I've merged it. But can you think about whether the issues I've outlined above make sense and how we can best structure the code moving forward?

Finally as an aside, I think introducing high level data structures on top of Redis is not a bad idea. e.g. `Protocol::Redis:Queue` or `Protocol::Redis::Map` etc. These can provide a "nice" interface, including mapping between Redis (the methods) and high level data structures.

**Comment by ioquatix** [comment]
FYI, a while ago, we used a script to generate all the method stubs from the Redis documentation.

https://github.com/socketry/protocol-redis/blob/main/bake/protocol/redis/generate.rb

**Comment by nburwell** [comment]
Hi @ioquatix , you bring up good points about avoiding methods that are not 1:1 with Redis commands. 

> What we have here is an extension of those methods around type coercion. As you said with eval too... It's easier if we just expose the bare methods with the arguments, and provide other constructs that make it convenient for the user.

I think that makes sense, and the more context I get with this gem and others in the async family, perhaps this gem isn't the right place for it at all? You have `async-redis` which is the gem that defines the actual `Client` object.  Should `async-redis` define those high level data structures that are optional to use -- and keep this gem as thin as possible?

Assuming we went that direction, I like your suggestion of having better constructs for how data is converted (and could provide aliases to assist developers porting code over from the existing redis gem)

**Comment by ioquatix** [comment]
I think what we can do is make the compatibility methods not part of the default methods.

Probably we can introduce separate methods for `redis-rb` compatibility.

I think this biases users to consider "Do I need compatibility with `redis-rb`?" and they may think about using the more simple/standard/direct methods.

What about this plan:

1. Let's put the methods into a separate module.
2. Let's document how to sub-class client and add the compatible methods. https://github.com/socketry/async-redis/blob/main/lib/async/redis/client.rb#L32

**Pull request merged**
